### ISSUE TITLE
Cleanup unused OAuth2 scheme from API

### ISSUE THREAD

**Issue by valb3r** [adorsys/open-banking-gateway#1148]
OAuth2 scheme in OpenBanking API is not used, instead request signing is used we need to fix that 
```
  securitySchemes:
    BearerAuthOAuth:
      description: |
        Bearer Token.
      type: http
      scheme: bearer
    accessCode:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: "http://example.com/oauth/auth"
          tokenUrl: "http://example.com/oauth/token"
          scopes:
            write: allows modifying resources
            read: allows reading resources
```
