### ISSUE TITLE
Rename configuration parameter 'cookie'

### ISSUE THREAD

**Issue by valb3r** [adorsys/open-banking-gateway#596]
Rename this section of application.yml and others:
```
cookie:
  secure: false # localhost-only - TODO application-dev.yml for dev env?
  max-age: PT300S
  http-only: true
  path: /
  same-site: Strict
```
to 
```
cookie-builder:
  secure: false # localhost-only - TODO application-dev.yml for dev env?
  max-age: PT300S
  http-only: true
  same-site: Strict
```
(and drop path section, path section should be validated when building cookie and dropped
